### ISSUE TITLE
Fehler abfangen, wenn keine Daten

### ISSUE THREAD

**Issue by Pix---** [klein0r/ioBroker.luftdaten#8]
Falls der Sensor keine Daten liefert, meldet der Adapter einen Fehler:

`2018-11-20 20:35:01.489  - [31merror[39m: luftdaten.0 TypeError: Cannot read property 'sensordatavalues' of undefined
    at Request._callback (/Users/pix/Documents/iobroker/node_modules/iobroker.luftdaten/main.js:90:51)
    at Request.self.callback (/Users/pix/Documents/iobroker/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
2018-11-20 20:35:01.992  - [32minfo[39m: luftdaten.0 terminating
`

Der sollte noch besser abgefangen werden.

Und wie in Issue 1 schone rwähnt, bitte Ordner _widgets_ löschen.

**Comment by Pix---** [comment]
Sorry, Problem lag  bei mir. Meine node-Installation war kaputt und request wurden nicht mehr korrekt behandelt. Alle Skripte und Adapter, die Daten aus dem Netz verarbeiteten sind durchgedreht.

Also: kein Fehler im Adapter, alles gut.

**Comment by Pix---** [comment]
Jetzt ist der Fehler heute wieder aufgetaucht und die anderen Teile des Systems sind in Ordnung.
`2018-12-24 10:40:03.791  - [31merror[39m: luftdaten.0 uncaught exception: Cannot read property 'sensordatavalues' of undefined
2018-12-24 10:40:03.791  - [31merror[39m: luftdaten.0 TypeError: Cannot read property 'sensordatavalues' of undefined
    at Request._callback (/Users/pix/Documents/iobroker/node_modules/iobroker.luftdaten/main.js:90:52)
    at Request.self.callback (/Users/pix/Documents/iobroker/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
2018-12-24 10:40:04.295  - [32minfo[39m: luftdaten.0 terminating
2018-12-24 10:40:04.304  - [32minfo[39m: host.MacMini.local instance system.adapter.luftdaten.0 terminated with code 0 (OK)`

Sieh es Dir doch nochmal an.

**Comment by Pix---** [comment]
Habe immernoch diesen Fehler: 
`[31merror[39m: luftdaten.0 TypeError: Cannot read property 'sensordatavalues' of undefined
    at Request._callback (/Users/pix/Documents/iobroker/node_modules/iobroker.luftdaten/main.js:90:52)
    at Request.self.callback (/Users/pix/Documents/iobroker/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pix/Documents/iobroker/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
2019-03-25 18:00:09.110  - [32minfo[39m: luftdaten.0 terminating`

Hast du diesen Fix von stabilostick vom letzten Juni gesehen?
https://forum.iobroker.net/post/159396

Er ändert quasi nur Zeile 87 der main.js
https://github.com/klein0r/ioBroker.luftdaten/blob/ba55b4da8610134b317662c74e88bb57d1428d88/main.js#L87
und bringt die Bedingung `(content.length > 0) ` ins Spiel.

Gruß
Pix

**Comment by klein0r** [comment]
Soll jetzt passen
